server:
  port: 8081

#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/newnews?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true


#配置mybatis实体和xml映射
mybatis:
  #mapper位置
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: come.example.demo.entity